edition             = "2021"
format_macro_bodies = true
format_strings      = true
imports_granularity = "Crate"
reorder_impl_items  = true
reorder_imports     = true
reorder_modules     = true
group_imports       = "StdExternalCrate"
wrap_comments       = true
